package ui

// Page constants for navigation
const (
	PageMainMenu                      = "mainMenu"
	PageEcsList                       = "ecsList"
	PageEcsDetail                     = "ecsDetail"
	PageSecurityGroups                = "securityGroups"
	PageSecurityGroupDetail           = "securityGroupDetail"
	PageSecurityGroupRules            = "securityGroupRules"
	PageSecurityGroupInstances        = "securityGroupInstances"
	PageInstanceSecurityGroups        = "instanceSecurityGroups"
	PageDnsDomains                    = "dnsDomains"
	PageDnsRecords                    = "dnsRecords"
	PageSlbList                       = "slbList"
	PageSlbDetail                     = "slbDetail"
	PageSlbListeners                  = "slbListeners"
	PageSlbVServerGroups              = "slbVServerGroups"
	PageSlbVServerGroupBackendServers = "slbVServerGroupBackendServers"
	PageOssBuckets                    = "ossBuckets"
	PageOssObjects                    = "ossObjects"
	PageRdsList                       = "rdsList"
	PageRdsDetail                     = "rdsDetail"
	PageRdsDatabases                  = "rdsDatabases"
	PageRdsAccounts                   = "rdsAccounts"
	PageRedisList                     = "redisList"
	PageRedisAccounts                 = "redisAccounts"
	PageRocketMQList                  = "rocketmqList"
	PageRocketMQTopics                = "rocketmqTopics"
	PageRocketMQGroups                = "rocketmqGroups"
)
